In [1]:
data_dict = {
    "label" :"link"
}

In [1]:
base_dir = "./Data_images"

In [3]:
import os
import requests
from PIL import Image
from io import BytesIO

# Hàm tải và lưu ảnh
def tai_va_luu_anh(url, path_to_save):
    try:
        response = requests.get(url)
        if response.status_code == 200:
            img = Image.open(BytesIO(response.content))

            # Kiểm tra nếu ảnh là trong chế độ RGBA, chuyển nó sang RGB
            if img.mode == 'RGBA':
                img = img.convert('RGB')

            img.save(path_to_save)
            print(f"Đã lưu: {path_to_save}")
        else:
            print(f"Lỗi khi tải ảnh từ {url}: Status code {response.status_code}")
    except Exception as e:
        print(f"Không thể tải ảnh từ {url}. Lỗi: {e}")

# Giả sử `base_dir` và `data_dict` đã được định nghĩa
# Duyệt qua từ điển và tải ảnh
for label, urls in data_dict.items():
    # Tạo thư mục cho mỗi label nếu chưa tồn tại
    label_dir = os.path.join(base_dir, label)  # Sử dụng trực tiếp tên label
    os.makedirs(label_dir, exist_ok=True)
    
    # Tải và lưu mỗi ảnh trong list
    for i, url in enumerate(urls):
        file_name = f"anh_{i}.jpg"  # Đặt tên file
        path_to_save = os.path.join(label_dir, file_name)
        tai_va_luu_anh(url, path_to_save)

Không thể tải ảnh từ l. Lỗi: Invalid URL 'l': No scheme supplied. Perhaps you meant https://l?
Không thể tải ảnh từ i. Lỗi: Invalid URL 'i': No scheme supplied. Perhaps you meant https://i?
Không thể tải ảnh từ n. Lỗi: Invalid URL 'n': No scheme supplied. Perhaps you meant https://n?
Không thể tải ảnh từ k. Lỗi: Invalid URL 'k': No scheme supplied. Perhaps you meant https://k?


In [5]:
import glob
import numpy as np
import os
from PIL import Image

    
def doc_va_chuyen_doi_anh_voi_nhan(thu_muc, label, target_size=(128, 128)):
    data_arrays = []
    labels = []
    
    # Include both JPG and PNG files in the search pattern
    for file_path in glob.glob(os.path.join(thu_muc, "*.*")):
        if file_path.lower().endswith(('.png', '.jpg', '.jpeg')):
            img = Image.open(file_path).convert('RGB')  # Convert to RGB
            img_resized = img.resize(target_size)
            img_array = np.array(img_resized) / 255.0
            #print(img_array.shape)  # Debugging to check shape
            data_arrays.append(img_array)
            labels.append(label)
    
    return np.array(data_arrays), np.array(labels)

data_train = []
labels_train = []
data_test = []
labels_test = []

# Sử dụng hàm cho mỗi thư mục nhãn
for label in os.listdir(base_dir):
    full_path = os.path.join(base_dir, label)
    print(full_path)
    data, labels = doc_va_chuyen_doi_anh_voi_nhan(full_path, label)
    
    # Giả sử chia 90% đầu làm dữ liệu huấn luyện và 10% còn lại làm dữ liệu kiểm tra
    split_idx = int(len(data) * 0.9)
    data_train.extend(data[:split_idx])
    labels_train.extend(labels[:split_idx])
    
    data_test.extend(data[split_idx:])
    labels_test.extend(labels[split_idx:])

# Chuyển các list thành numpy arrays
data_train = np.array(data_train)
labels_train = np.array(labels_train)
data_test = np.array(data_test)
labels_test = np.array(labels_test)

print(f"Dữ liệu huấn luyện: {data_train.shape}, Nhãn huấn luyện: {labels_train.shape}")
print(f"Dữ liệu kiểm tra: {data_test.shape}, Nhãn kiểm tra: {labels_test.shape}")


./Data_images\.ipynb_checkpoints
./Data_images\iPhone 15 + iPhone 15 Plus
./Data_images\iPhone 15 Pro + iPhone 15 Pro Max
./Data_images\Samsung A23
./Data_images\Samsung S24+S24plus
./Data_images\Samsung S24Ultra
./Data_images\Samsung Zflip 3+4
./Data_images\Samsung Zflip 5
./Data_images\Samsung Zfold 5
Dữ liệu huấn luyện: (3270, 128, 128, 3), Nhãn huấn luyện: (3270,)
Dữ liệu kiểm tra: (366, 128, 128, 3), Nhãn kiểm tra: (366,)


In [6]:
data_test.shape

(366, 128, 128, 3)

In [7]:
labels_test

array(['iPhone 15 + iPhone 15 Plus', 'iPhone 15 + iPhone 15 Plus',
       'iPhone 15 + iPhone 15 Plus', 'iPhone 15 + iPhone 15 Plus',
       'iPhone 15 + iPhone 15 Plus', 'iPhone 15 + iPhone 15 Plus',
       'iPhone 15 + iPhone 15 Plus', 'iPhone 15 + iPhone 15 Plus',
       'iPhone 15 + iPhone 15 Plus', 'iPhone 15 + iPhone 15 Plus',
       'iPhone 15 + iPhone 15 Plus', 'iPhone 15 + iPhone 15 Plus',
       'iPhone 15 + iPhone 15 Plus', 'iPhone 15 + iPhone 15 Plus',
       'iPhone 15 + iPhone 15 Plus', 'iPhone 15 + iPhone 15 Plus',
       'iPhone 15 + iPhone 15 Plus', 'iPhone 15 + iPhone 15 Plus',
       'iPhone 15 + iPhone 15 Plus', 'iPhone 15 + iPhone 15 Plus',
       'iPhone 15 + iPhone 15 Plus', 'iPhone 15 + iPhone 15 Plus',
       'iPhone 15 + iPhone 15 Plus', 'iPhone 15 + iPhone 15 Plus',
       'iPhone 15 + iPhone 15 Plus', 'iPhone 15 + iPhone 15 Plus',
       'iPhone 15 + iPhone 15 Plus', 'iPhone 15 + iPhone 15 Plus',
       'iPhone 15 + iPhone 15 Plus', 'iPhone 15 Pro + iPhone 1

In [8]:
from sklearn.preprocessing import LabelEncoder

# Tạo một encoder
encoder = LabelEncoder()

# Đưa nhãn văn bản về dạng số nguyên
labels_train_encoded = encoder.fit_transform(labels_train)
labels_test_encoded = encoder.fit_transform(labels_test)
# In nhãn sau khi được mã hóa để kiểm tra
print(labels_train_encoded)
print(labels_test_encoded)

[6 6 6 ... 5 5 5]
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]


In [8]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [9]:
from tensorflow.keras.utils import to_categorical

# Chuyển đổi nhãn sang dạng one-hot
labels_train_one_hot = to_categorical(labels_train_encoded)
labels_test_one_hot = to_categorical(labels_test_encoded)

In [10]:
labels_train_one_hot

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [12]:
entries = os.listdir(base_dir)
folder_count = sum(os.path.isdir(os.path.join(base_dir, entry)) for entry in entries)
print(folder_count)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, Input

model = Sequential([
    Input(shape=(128, 128, 3)),  # Sử dụng Input layer để xác định kích thước đầu vào
    Conv2D(32, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),
    Flatten(),
    Dense(512, activation='relu'),
    Dropout(0.5),
    Dense(folder_count, activation='softmax')  # `len(data_dict)` là số lớp
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

8


In [13]:
import tensorflow as tf

# train_dataset = tf.data.Dataset.from_tensor_slices((data_train, labels_train_one_hot)).batch(32).repeat()
# test_dataset = tf.data.Dataset.from_tensor_slices((data_test, labels_test_one_hot)).batch(32).repeat()

# Huấn luyện mô hình validation_data=(data_test, labels_test_one_hot)
history = model.fit(
    data_train, labels_train_one_hot,
    epochs=10, # Số lượng bước huấn luyện mỗi epoch
)

Epoch 1/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 22s 196ms/step - accuracy: 0.1582 - loss: 2.1726
Epoch 2/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 20s 192ms/step - accuracy: 0.3685 - loss: 1.7585
Epoch 3/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 20s 197ms/step - accuracy: 0.4832 - loss: 1.4662
Epoch 4/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 20s 193ms/step - accuracy: 0.6265 - loss: 1.0759
Epoch 5/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 20s 194ms/step - accuracy: 0.7549 - loss: 0.7550
Epoch 6/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 20s 193ms/step - accuracy: 0.8590 - loss: 0.4350
Epoch 7/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 20s 194ms/step - accuracy: 0.9124 - loss: 0.2756
Epoch 8/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 20s 193ms/step - accuracy: 0.9451 - loss: 0.2122
Epoch 9/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 20s 197ms/step - accuracy: 0.9586 - loss: 0.1547
Epoch 10/10
103/103 ━━━━━━━━━━━━━━━━━━━━ 20s 196ms/step - accuracy: 0.9657 - loss: 0.1432


In [15]:
model.metrics_names

['loss', 'compile_metrics']

In [16]:
model.evaluate(data_test,labels_test_one_hot)

12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - accuracy: 0.5647 - loss: 2.2152


[2.1100332736968994, 0.568306028842926]

In [17]:
from sklearn.metrics import classification_report
import numpy as np

predictions = model.predict(data_test)

predicted_classes = np.argmax(predictions, axis=1)

actual_classes = np.argmax(labels_test_one_hot, axis=1)

report = classification_report(actual_classes, predicted_classes)
print(report)

12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step
              precision    recall  f1-score   support

           0       0.61      0.47      0.53        49
           1       0.80      0.78      0.79        51
           2       0.66      0.68      0.67        40
           3       0.57      0.52      0.55        46
           4       0.48      0.61      0.53        51
           5       0.51      0.42      0.46        50
           6       0.45      0.52      0.48        29
           7       0.48      0.54      0.51        50

    accuracy                           0.57       366
   macro avg       0.57      0.57      0.57       366
weighted avg       0.57      0.57      0.57       366



In [18]:
from sklearn.metrics import confusion_matrix
import numpy as np

# Giả sử predicted_classes là nhãn dự đoán từ mô hình của bạn
# và actual_classes là nhãn thực tế của tập kiểm tra
 # [[41  7  1  0  2]
 # [ 1  3  1  3  3]
 # [ 8  0 34  1  8]
 # [ 7  1  1 15  5]
 # [ 4  0  7  7 32]]
# Tính ma trận nhầm lẫn
cm = confusion_matrix(actual_classes, predicted_classes)

# In ma trận nhầm lẫn
print(cm)

# Tính TP, TN, FP, FN cho mỗi lớp
TP = np.diag(cm)
FP = cm.sum(axis=0) - np.diag(cm)
FN = cm.sum(axis=1) - np.diag(cm)
TN = cm.sum() - (FP + FN + TP)

# In ra số lượng TP, TN, FP, FN cho mỗi lớp
print("True Positives: ", TP)
print("False Positives: ", FP)
print("True Negatives: ", TN)
print("False Negatives: ", FN)


[[23  2  1  6  3  4  4  6]
 [ 2 40  1  5  0  0  0  3]
 [ 0  2 27  0  1  4  2  4]
 [ 2  0  2 24 11  2  1  4]
 [ 5  1  4  3 31  3  3  1]
 [ 2  2  5  0 11 21  2  7]
 [ 0  2  1  1  1  5 15  4]
 [ 4  1  0  3  7  2  6 27]]
True Positives:  [23 40 27 24 31 21 15 27]
False Positives:  [15 10 14 18 34 20 18 29]
True Negatives:  [302 305 312 302 281 296 319 287]
False Negatives:  [26 11 13 22 20 29 14 23]


In [19]:
model.save('e-commerce-model.keras')

In [20]:
import joblib

# Lưu encoder
joblib.dump(encoder, 'label_encoder.pkl')

['label_encoder.pkl']

In [21]:
# run this cell
import requests
import numpy as np
from keras.preprocessing import image
from keras.models import load_model
import joblib

url = 'http://localhost:3004/imgSearch'

# Tải LabelEncoder
encoder = joblib.load('label_encoder.pkl')

# Chuẩn bị ảnh
img_path = './Data_check/anh_13.jpg'
img = image.load_img(img_path, target_size=(128, 128))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
img_array /= 255.0

# Dự đoán
predictions = model.predict(img_array)

# Lấy tất cả nhãn từ encoder
all_labels = encoder.classes_

# Hiển thị xác suất dự đoán cho mỗi nhãn
print("Xác suất dự đoán cho mỗi nhãn:")
for label, prob in zip(all_labels, predictions[0]):
    print(f"{label}: {prob*100:.2f}%")


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
Xác suất dự đoán cho mỗi nhãn:
Samsung A23: 0.02%
Samsung S24+S24plus: 0.00%
Samsung S24Ultra: 2.91%
Samsung Zflip 3+4: 0.04%
Samsung Zflip 5: 0.03%
Samsung Zfold 5: 0.40%
iPhone 15 + iPhone 15 Plus: 0.01%
iPhone 15 Pro + iPhone 15 Pro Max: 96.60%
